[versions]
# PLUGINS
kotlin-jvm = "2.3.0"
buildconfig = "3.1.0"

# ANNOTATIONS
lombok = "1.18.46"
jetbrains = "26.1.0"

# DATA FORMAT
jackson = "2.21.3"

junit-launcher = "1.14.4"

# TESTING
mockk = "1.14.9"

spock = "2.4-groovy-4.0"

[libraries]
kotlin-jvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-jvm" }

# ANNOTATIONS
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jetbrains = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }

# DATA FORMAT
json = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
properties = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-properties", version.ref = "jackson" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }

junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-launcher" }

# TESTING
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

spock = { module = "org.spockframework:spock-core", version.ref = "spock" }

[bundles]
jackson = ["json", "yaml", "properties", "jackson-kotlin"]

[plugins]
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
