[versions]
# PLUGINS
kotlin = "2.3.0"
buildconfig = "6.0.9"

# TESTING
mockk = "1.14.9"

[libraries]
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
